configuration/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import pretty_update_status.urls as update_status
import pretty_addFriend.urls as pretty_addFriend
import pretty_stats.urls as pretty_stats
import pretty_profile_page.urls as profile_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status,namespace='update-status')),
    url(r'^add-friend/', include(pretty_addFriend,namespace='add-friend')),
	url(r'^stats/', include(pretty_stats,namespace='pretty_stats')),
    url(r'^profile-page/', include(profile_page,namespace='profile-page')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent=True), name='index'),
]

pretty_addFriend/urls.py
from django.conf.urls import url
from .views import index, friend_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', friend_post, name='add_friend'),

]

pretty_profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

pretty_stats/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

pretty_update_status/urls.py
from django.conf.urls import url
from .views import index, status_update

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', status_update, name='add_status'),
]

pretty_addFriend/models.py
from django.db import models

# Create your models here.

class AddFriend(models.Model):
    name = models.TextField(max_length=35)
    website = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

pretty_profile_page/models.py
from django.db import models

# Create your models here.

class Expertise(models.Model):
    name = models.TextField()
    
class Profile(models.Model):
    name = models.CharField(max_length = 27)
    birthday = models.DateTimeField()
    gender = models.TextField()
    expertise = models.ManyToManyField(Expertise)
    description = models.TextField()
    email = models.EmailField()


    

pretty_stats/models.py
from django.db import models

# Create your models here.

pretty_update_status/models.py
from django.db import models

class Status(models.Model):
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

pretty_addFriend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'This part has to be filled',
        'invalid': 'Not a valid URL',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Name', required=True, max_length=35, widget=forms.TextInput(attrs=attrs), error_messages=error_messages)
    website = forms.CharField(label='Website', required=True, widget=forms.URLInput(attrs=attrs), error_messages=error_messages)

pretty_update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please fill this input',
    }
    description_attrs = {
        'type': 'text',
        'cols': 100,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'How are you today?'
    }

    message = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, label="")

pretty_addFriend/views.py
from django.shortcuts import render
from .models import AddFriend
from django.http import HttpResponseRedirect
from .forms import Friend_Form

# Create your views here.
response = {}
html = 'add_friend.html'

def index(request):
    response['Friend_form'] = Friend_Form
    addfriend = AddFriend.objects.all()
    response['addfriend'] = addfriend
    return render(request, html , response)

def friend_post(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['website'] = request.POST['website']
        addfriend = AddFriend(name=response['name'], website=response['website'])
        addfriend.save()      
    return HttpResponseRedirect('/add-friend/')

pretty_profile_page/views.py
from django.shortcuts import render
from .models import Profile, Expertise
from django.core.files.images import ImageFile

# Create your views here.

#expertise1 = Expertise.objects.create(name = "Marketing")
#expertise2 = Expertise.objects.create(name = "Dancing")
#expertise3 = Expertise.objects.create(name = "Fishing")


##expertise = Expertise(name='Baba')
##expertise1 = Expertise(name='Sheperd')
##expertise2 = Expertise(name='Saaa')
##expertise.save()
##expertise1.save()
##expertise2.save()
##new_profile = Profile.objects.create(id=2, image='',
##                                      name='David Bowie',
##                                      birthday='1947-01-08 14:14:00',
##                                      gender='Male',
##                                      description='Ziggy Stardust',
##                                      email='david@bowie.com')
##
##new_profile.expertise.add(expertise, expertise1, expertise2)
##
##
##
##
##
##profile = Profile.objects.create(image='', name="Coba", birthday='1998-01-07 03:00:00',
##                                 gender= 'Female', description= 'ABC as easy as 123',
##                                 email= 'coba@ui.ac.id')

#profile.image = ''
#profile.name= "Coba"
#profile.birthday = '1998-01-07 03:00:00'
#profile.gender = 'Female'
#profile.expertise = [expertise1, expertise2, expertise3]
#profile.description = 'ABC as easy as 123'
#profile.email = 'coba@ui.ac.id'

response = {}
def index (request):
    profile = Profile.objects.all()
    response['author'] = 'pretty'
    response['profile'] = profile
    return render(request, 'profile_page.html', response)

pretty_stats/views.py
from django.shortcuts import render, redirect
from datetime import datetime, date
from pretty_addFriend.models import AddFriend
from pretty_update_status.models import Status

#from some other views.py import name, friendCounter, feedCounter
# Create your views here.


# Enter your name here
name1 = 'Team PrettyPrettyWebsite' # variable to import maybe?

# Create your views here.
def index(request):
	frNumber = AddFriend.objects.count()
	feedNo = Status.objects.count()
	lastPost = Status.objects.last()
	response = {'name': name1, 'frNo': frNumber, 'feed': feedNo, 'LPost': lastPost}

	return render(request, 'content.html', response)

pretty_update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
# Create your views here.
response = {}
def index(request):
    response['author'] = "Team PrettyPrettyWebsite"
    status = Status.objects.all()
    response['status'] = status
    html = 'pretty_update_status.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def status_update(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        status = Status(message=response['message'])
        status.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

pretty_addFriend/templates/add_friend.html
{% extends "base.html" %}

{% block content %}
<section name="form">
	<h2 style="color:DarkTurquoise">Friend List</h2>
	<form id="form" method="POST" action="{% url 'add-friend:add_friend' %}">
		{% csrf_token %}
		{{ Friend_form }}
		<br>
		<button type="submit" class="btn btn-lg btn-block btn-info" id="submit" style="float:left">Submit</button>
	</form>
</section>
<br/>
<hr/>

<table class="table">
	<thead>
		<th>Name</th>
		<th>Website</th>
		<th>Added on</th>
	</thead>
	<tbody>
		<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
		{% for i in addfriend reversed %}
			<td> {{i.name}} </td>
			<td> <a href="{{i.website}}"> {{i.website}} </a> </td>
			<td> {{i.created_date}} </td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

pretty_profile_page/templates/profile_page.html
<style>
.expertise {
    background-color: DarkTurquoise;
    border-width: thin;
    border-radius: 10px;
    padding: 5px;
    padding-bottom: 3px;
    padding-top: 3px;
    display: inline-block;
}
</style>

{% extends 'base.html' %}
{% block content %}

<head>
    <meta name="description" content="Profile Page">
</head>
<h1 class="main-title" style="color:DarkTurquoise">Profile</h1>
{% for profilepage in profile %}
<div class="content-wrapper">
    <br/>
    <br/>
    <div class="profile-header" style = "text-align: center">
        <img class="img-circle" src="../static/giphy.gif" style="height:200px;widht:200px" align= "center">
        <h3>{{ profilepage.name }}</h3>
    </div>
    <br/>
    <br/>

<table border="0" align="center" style="text-align: left ;border:0px;" >
        <tr>
            <td> Birthday </td>
            <td style="padding-left:25px"; "padding-bottom: 10px"> {{ profilepage.birthday }}</td>
        </tr>

        <tr>
            <td> Gender </td>
            <td style="padding-left:25px"> {{ profilepage.gender }}</td>
        </tr>

        <tr>
            <td> Expertise </td>
            <td style="padding-left:25px">
                {% for expertise in profilepage.expertise.all %}
                     <div class="expertise" style="background-color:DarkTurquoise">
                    {{ expertise.name }}
                     </div>
                {% endfor %}
            </td>
        </tr>

        <tr>
            <td> Description </td>
            <td style="padding-left:25px"> {{ profilepage.description }} </td>
        </tr>

        <tr>
            <td> Email </td>
            <td style="padding-left:25px"> {{ profilepage.email }} </td>
        </tr>

</table>
<br><br>
</div>
{% endfor %}
{% endblock %}

pretty_stats/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="stats">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <title>
        {% block title %} PrettyPrettyWebsite {% endblock %}
    </title>

</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

pretty_stats/templates/content.html
<!-- Codes by HTML.am -->
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- HTML Code -->
<div class="title">Statistics</div>
<div class="container" id="profile-image">
	<br/><br/><br/>

	<p style="float: left;">
		<center><img src="{% static "images/giphy.gif" %}" class="circle"></p>
		<className> <br/>
			<div class="tname" style="font-size:24px">
		{{ name }}
	</div>
</className>
		<div style="clear: left;">
<center>

		</div>
		<div class="bottom">
		<FRNO style="font-size:20px">Friends : {{ frNo }} </FRNO>

		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


		<FEED style="font-size:20px"> Feed: {{feed}} Post </FEED>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		<LPOST style="font-size:22px; color:DarkTurquoise"> Latest Post</LPOST>
			<br/>
			<br/>
			{% if LPost %}
		<img src="{% static "images/giphy.gif" %}" class="circle-image">
			<name style="font-size:18px"> {{name}} </name>

			<br/>
			<br/>

		<LastPost>
			{{LPost.message|linebreaks}}
		</LastPost>
		<LastPostDate style="font-style: italic;">
			{{LPost.created_date}}
		</LastPostDate>
		{% else %}
		<div class="alert alert-danger text-center" style="width:25%">
			<strong>Oops!</strong> You haven't post anything.
		</div>
		{% endif %}

		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>

	</div>
	</div>

	{% endblock %}

pretty_stats/templates/partials/footer.html
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<footer>&copy; Made by not so pretty person</footer>

pretty_stats/templates/partials/header.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<ul>
  <li><a href="/update-status">Status</a></li>
  <li><a href="/profile-page">Profile</a></li>
  <li><a href="/add-friend">Friends</a></li>
  <li><a href="/stats">Stats</a></li>
  <li style="float:right"><a href="/update-status">PrettyMe</a></li>
</ul>

</body>
</html>

pretty_stats/templates/profile_pic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>



</body>
</html>

pretty_update_status/templates/pretty_update_status.html
{% extends "base.html" %}
{% block content %}

<section name="input-list" id="input-list" style="min-height: 200px; width: 100%">
  <div class="container">
    <h2 style="color:DarkTurquoise">Update Status</h2>
    <form id="status_form" method="POST" action="{% url 'update-status:add_status' %}">
      {% csrf_token %}
      {{ status_form }}
      <br/>
      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
      <br/>
      <br/>
      <br/>
    </form>
  </div>
</section>
<section name="status_table" id="status_table" style="min-height: 200px; width: 100%">
  <div class="container">
    <div class="flex">
      {% if status %}
      {% for data in status reversed %}
      <div class="flex-item">
        <div class="status">
          <strong>
            <img src="../static/images/giphy.gif" class="circle-image" />
            {{author}}
          </strong>
          <div class="status-message">
            {{data.message|linebreaks}}
          </div>
          <div class="status-date-added">
            {{data.created_date}}
          </div>
          <hr/>
          <br/>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="alert alert-danger text-center">
        <strong>Oops!</strong> You haven't post anything.
      </div>
    {% endif %}
    </div>
  </div>
</section>
{% endblock %}